### ISSUE TITLE
Future of this package

### ISSUE THREAD

**Issue by Keno** [sygreer/SoapySDR.jl#1]
Hi @sygreer,

@staticfloat and I had some SDRing to do, so we took this package, and did a bit of an expansion to fix it up for recent upstream versions, add a high level API, add TX support, add automatic installation of the binary dependencies etc. It's by no means complete, but I think it's getting to a point where it'd be useful to register the package. Before I do, I wanted to check with you to what extent you wanted to be involved. I understand this was a class project, so if you just want us to do whatever, just say that :). In either case, we could think about pushing the code here, or maybe moving the package to JuliaTelecom or a similar org. Let me know :).

**Comment by Keno** [comment]
Link to our changes: https://github.com/Keno/SoapySDR.jl

**Comment by sygreer** [comment]
Hi @Keno and @staticfloat,

Glad y'all are taking a look at the package! You can do what you think is best for the future of the package; just let me know where it ends up if you want to move it and I can change the readme to point people to it. Or I could add you both as collaborators if you'd like to keep the package here

**Comment by Keno** [comment]
Ok, sounds good. I'll see if the JuliaTelecom folks want it. If so, probably the best thing to do is to set it up there as a new repo (keeping the history, but not a fork, since GitHub likes hiding forks), so you can keep the repo archived here as your class project and then just point people to the other repo with a link in the README.

**Comment by Keno** [comment]
To close the loop on this, SoapySDR now lives under JuliaTelecom at https://github.com/JuliaTelecom/SoapySDR.jl and is registered in the general registry as of this morning.
